info:
  contact: {}
  license: {}
paths:
  /api/v1/activities:
    get:
      parameters:
      - description: Page
        in: query
        name: Page
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 活动列表
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: 活动主题
        in: formData
        name: Theme
        required: true
        type: string
      - description: 活动时间
        in: formData
        name: Time
        required: true
        type: integer
      - description: 活动地址
        in: formData
        name: Address
        required: true
        type: string
      - description: 活动内容
        in: formData
        name: Content
        required: true
        type: string
      - description: 活动人数
        in: formData
        name: Totol
        required: true
        type: integer
      - description: 1正常显示,0不显示
        in: formData
        name: Status
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: '{"code":201,"data":{},"msg":"ok"}'
          schema:
            type: string
        "400":
          description: '{"code":400,"data":null,"msg":"请求参数错误"}'
          schema:
            type: string
        "500":
          description: '{"code":500,"data":null,"msg":"添加文章失败"}'
          schema:
            type: string
      summary: 添加活动
  /api/v1/activities/{id}:
    get:
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 活动详情
  /api/v1/applies:
    get:
      parameters:
      - description: Page
        in: query
        name: Page
        required: true
        type: integer
      - description: 活动id
        in: query
        name: ActivityId
        type: integer
      - description: 用户id
        in: query
        name: UserId
        type: integer
      - description: 1通过,0不通过
        in: query
        name: Status
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 活动报名列表
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: 活动id
        in: formData
        name: ActivityId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: '{"code":201,"data":{},"msg":"ok"}'
          schema:
            type: string
        "400":
          description: '{"code":400,"data":null,"msg":"请求参数错误"}'
          schema:
            type: string
        "500":
          description: '{"code":500,"data":null,"msg":"添加文章失败"}'
          schema:
            type: string
      summary: 申请活动报名
  /api/v1/banners:
    get:
      parameters:
      - description: page
        in: query
        name: page
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 首页封面列表
  /api/v1/dynamics:
    get:
      parameters:
      - description: Page
        in: query
        name: Page
        required: true
        type: integer
      - description: Status
        in: query
        name: Status
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 党建动态列表
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: 党建动态标题
        in: formData
        name: Title
        required: true
        type: string
      - description: 党建动态内容
        in: formData
        name: Content
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: '{"code":201,"data":{},"msg":"ok"}'
          schema:
            type: string
        "400":
          description: '{"code":400,"data":null,"msg":"请求参数错误"}'
          schema:
            type: string
        "500":
          description: '{"code":500,"data":null,"msg":"添加文章失败"}'
          schema:
            type: string
      summary: 添加党建动态
  /api/v1/dynamics/{id}:
    get:
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 党建动态详情
  /api/v1/images:
    delete:
      consumes:
      - multipart/form-data
      parameters:
      - description: 活动主题
        in: query
        name: ImageName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: '{"code":204,"data":null,"msg":"删除成功"}'
          schema:
            type: string
        "500":
          description: '{"code":500,"data":null,"msg":"删除失败"}'
          schema:
            type: string
      summary: 删除图片
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: 上传图片
        in: formData
        name: File
        required: true
        type: file
      produces:
      - application/json
      responses:
        "201":
          description: '{"code":201,"data":{},"msg":"ok"}'
          schema:
            type: string
        "400":
          description: '{"code":400,"data":null,"msg":"图片验证失败"}'
          schema:
            type: string
        "500":
          description: '{"code":500,"data":null,"msg":"上传失败"}'
          schema:
            type: string
      summary: 上传图片
  /api/v1/miens:
    get:
      parameters:
      - description: 类型1团队风采,2活动风采
        in: query
        name: Type
        type: integer
      - description: Page
        in: query
        name: Page
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 风采列表
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: 类型1团队风采,2活动风采
        in: formData
        name: Type
        required: true
        type: string
      - description: 风采标题
        in: formData
        name: Title
        required: true
        type: string
      - description: 风采内容
        in: formData
        name: Content
        required: true
        type: string
      - description: 1正常显示,0不显示
        in: formData
        name: Status
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: '{"code":201,"data":{},"msg":"ok"}'
          schema:
            type: string
        "400":
          description: '{"code":400,"data":null,"msg":"请求参数错误"}'
          schema:
            type: string
        "500":
          description: '{"code":500,"data":null,"msg":"添加文章失败"}'
          schema:
            type: string
      summary: 添加风采
  /api/v1/miens/{id}:
    get:
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 风采详情
  /api/v1/theoies:
    get:
      parameters:
      - description: page
        in: query
        name: Page
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 理论分享列表
  /api/v1/theoies/{id}:
    get:
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 理论详情
  /api/v1/theoy:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: 理论标题
        in: formData
        name: Title
        required: true
        type: string
      - description: 理论内容
        in: formData
        name: Content
        required: true
        type: string
      - description: 1正常显示,0不显示
        in: formData
        name: Status
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: '{"code":201,"data":{},"msg":"ok"}'
          schema:
            type: string
        "400":
          description: '{"code":400,"data":null,"msg":"请求参数错误"}'
          schema:
            type: string
        "500":
          description: '{"code":500,"data":null,"msg":"添加文章失败"}'
          schema:
            type: string
      summary: 添加理论分享
  /login:
    get:
      parameters:
      - description: username
        in: query
        name: username
        required: true
        type: string
      - description: password
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 登录
swagger: "2.0"
